FROM alpine:3.10

ENV PSU_AUTH_TOKEN="" \
  PSU_CONFIG="" \
  PSU_CONFIG_LIST_FORMAT="" \
  PSU_ENDPOINT_GROUP_INSPECT_FORMAT="" \
  PSU_ENDPOINT_GROUP_LIST_FORMAT="" \
  PSU_ENDPOINT_INSPECT_FORMAT="" \
  PSU_ENDPOINT_LIST_FORMAT="" \
  PSU_INSECURE="" \
  PSU_LOG_FORMAT="" \
  PSU_LOG_LEVEL="" \
  PSU_LOGIN_PRINT="" \
  PSU_PASSWORD="" \
  PSU_PROXY_ADDRESS="" \
  PSU_PROXY_ENDPOINT="" \
  PSU_STACK_DEPLOY_ENDPOINT="" \
  PSU_STACK_DEPLOY_ENV_FILE="" \
  PSU_STACK_DEPLOY_REPLACE_ENV="" \
  PSU_STACK_DEPLOY_STACK_FILE="" \
  PSU_STACK_INSPECT_ENDPOINT="" \
  PSU_STACK_INSPECT_FORMAT="" \
  PSU_STACK_LIST_ENDPOINT="" \
  PSU_STACK_LIST_FORMAT="" \
  PSU_STACK_REMOVE_ENDPOINT="" \
  PSU_STACK_REMOVE_STRICT="" \
  PSU_STATUS_FORMAT="" \
  PSU_TIMEOUT="" \
  PSU_URL="" \
  PSU_USER=""

COPY psu /usr/local/bin/psu

ENTRYPOINT ["/usr/local/bin/psu"]
