FROM alpine

ENV PSU_AUTHENTICATION_PASSWORD="" \
  PSU_AUTHENTICATION_USER="" \
  PSU_CONFIG="" \
  PSU_CONNECTION_INSECURE="" \
  PSU_CONNECTION_TIMEOUT="" \
  PSU_CONNECTION_URL="" \
  PSU_DEBUG="" \
  PSU_ENDPOINT_LIST_FORMAT="" \
  PSU_STACK_DEPLOY_ENDPOINT="" \
  PSU_STACK_DEPLOY_ENV_FILE="" \
  PSU_STACK_DEPLOY_REPLACE_ENV="" \
  PSU_STACK_DEPLOY_STACK_FILE="" \
  PSU_STACK_LIST_ENDPOINT="" \
  PSU_STACK_LIST_FORMAT="" \
  PSU_STACK_LIST_QUIET="" \
  PSU_STACK_LIST_SWARM="" \
  PSU_STACK_REMOVE_STRICT="" \
  PSU_STATUS_FORMAT="" \
  PSU_VERBOSE=""

COPY psu /usr/local/bin/psu

ENTRYPOINT ["/usr/local/bin/psu"]
