FROM alpine:3.10

ENV PSU_AUTH_TOKEN=""
ENV PSU_CONFIG=""
ENV PSU_CONFIG_LIST_FORMAT=""
ENV PSU_ENDPOINT_GROUP_INSPECT_FORMAT=""
ENV PSU_ENDPOINT_GROUP_LIST_FORMAT=""
ENV PSU_ENDPOINT_INSPECT_FORMAT=""
ENV PSU_ENDPOINT_LIST_FORMAT=""
ENV PSU_INSECURE=""
ENV PSU_LOG_FORMAT=""
ENV PSU_LOG_LEVEL=""
ENV PSU_LOGIN_PRINT=""
ENV PSU_PASSWORD=""
ENV PSU_PROXY_ADDRESS=""
ENV PSU_PROXY_ENDPOINT=""
ENV PSU_STACK_DEPLOY_ENDPOINT=""
ENV PSU_STACK_DEPLOY_ENV_FILE=""
ENV PSU_STACK_DEPLOY_REPLACE_ENV=""
ENV PSU_STACK_DEPLOY_STACK_FILE=""
ENV PSU_STACK_INSPECT_ENDPOINT=""
ENV PSU_STACK_INSPECT_FORMAT=""
ENV PSU_STACK_LIST_ENDPOINT=""
ENV PSU_STACK_LIST_FORMAT=""
ENV PSU_STACK_REMOVE_ENDPOINT=""
ENV PSU_STACK_REMOVE_STRICT=""
ENV PSU_STATUS_FORMAT=""
ENV PSU_TIMEOUT=""
ENV PSU_URL=""
ENV PSU_USER=""

COPY psu /usr/local/bin/psu

ENTRYPOINT ["/usr/local/bin/psu"]
