version: 2
jobs:
  release:
    docker:
      - image: goreleaser/goreleaser
    working_directory: /go/src/github.com/greenled/portainer-stack-utils
    steps:
      - checkout
      - setup_remote_docker:
      - run: |
          goreleaser --skip-publish --snapshot
